#!/usr/bin/env bash
set -euo pipefail

# Installs an exact-head candidate Function in the already-approved PR vCluster.
# The child XR is generated by the trusted Go evaluator, never copied from PR YAML.
repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
context=${PREVIEW_KUBE_CONTEXT:-kind-preview-platform}
name=${1:?host preview name required}
package=${2:?immutable Function package required}
child_xr=${3:?trusted child XR JSON required}
head=${4:?exact PR head required}

[[ $name =~ ^[a-z][a-z0-9-]{0,62}$ ]] || exit 2
[[ $package =~ ^ghcr\.io/[a-z0-9._/-]+@sha256:[a-f0-9]{64}$ ]] || exit 2
[[ $head =~ ^[a-f0-9]{40}$ ]] || exit 2
[[ -f $child_xr ]] || exit 2
host() { kubectl --context "$context" "$@"; }
guest() { kubectl --kubeconfig "$kubeconfig" "$@"; }

# 75 means Argo/Crossplane has not created the vCluster yet; the watcher retries.
if ! host -n "$name" get secret "vc-$name" -o jsonpath='{.data.config}' >/dev/null 2>&1; then
  echo "candidate-preview: virtual API is not available yet for $name" >&2
  exit 75
fi

umask 077
kubeconfig=$(mktemp /tmp/preview-candidate-guest.XXXXXXXX)
forward_log=$(mktemp /tmp/preview-candidate-forward.XXXXXXXX)
forward_pid=
cleanup() {
  if [[ -n $forward_pid ]]; then
    kill "$forward_pid" 2>/dev/null || true
    wait "$forward_pid" 2>/dev/null || true
  fi
  rm -f "$kubeconfig" "$forward_log"
}
trap cleanup EXIT

host -n "$name" get secret "vc-$name" -o jsonpath='{.data.config}' | base64 --decode > "$kubeconfig"
port=$(python3 - <<'PY'
import socket
with socket.socket() as listener:
    listener.bind(("127.0.0.1", 0))
    print(listener.getsockname()[1])
PY
)
python3 - "$kubeconfig" "$port" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
contents = path.read_text()
old = "https://localhost:8443"
if contents.count(old) != 1:
    raise SystemExit("candidate-preview: unexpected vCluster kubeconfig server")
path.write_text(contents.replace(old, f"https://localhost:{sys.argv[2]}"))
PY
host -n "$name" port-forward "pod/$name-0" "$port:8443" > "$forward_log" 2>&1 &
forward_pid=$!
for ((attempt=0; attempt<30; attempt++)); do
  if guest --request-timeout=3s get node >/dev/null 2>&1; then break; fi
  kill -0 "$forward_pid" 2>/dev/null || { cat "$forward_log" >&2; exit 1; }
  sleep 2
done
guest --request-timeout=5s get node >/dev/null

if ! helm --kubeconfig "$kubeconfig" status crossplane --namespace crossplane-system >/dev/null 2>&1; then
  echo "candidate-preview: installing Crossplane 2.4.0 in $name"
  helm --kubeconfig "$kubeconfig" upgrade --install crossplane crossplane \
    --repo https://charts.crossplane.io/stable --version 2.4.0 \
    --namespace crossplane-system --create-namespace --wait --timeout 5m >/dev/null
fi
guest wait --for=create deploymentruntimeconfig.pkg.crossplane.io/default --timeout=2m >/dev/null

cat <<EOF | guest apply -f - >/dev/null
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-preview-resources
spec:
  package: $package
EOF
for ((attempt=0; attempt<150; attempt++)); do
  if guest get function.pkg.crossplane.io/function-preview-resources -o json | python3 -c '
import json,sys
obj=json.load(sys.stdin)
package=sys.argv[1]
generation=obj["metadata"].get("generation", 0)
conditions=obj.get("status", {}).get("conditions", [])
healthy=any(c.get("type")=="Healthy" and c.get("status")=="True" and c.get("observedGeneration",0)>=generation for c in conditions)
installed=any(c.get("type")=="Installed" and c.get("status")=="True" and c.get("observedGeneration",0)>=generation for c in conditions)
sys.exit(0 if healthy and installed and obj.get("status",{}).get("currentIdentifier")==package else 1)
' "$package"; then break; fi
  sleep 2
done
(( attempt < 150 )) || { echo "candidate-preview: candidate Function did not become current and healthy" >&2; exit 1; }

guest apply -f "$repo_root/platform/crossplane/rbac/composed-resources.yaml" \
  -f "$repo_root/platform/crossplane/xrd.yaml" \
  -f "$repo_root/platform/crossplane/compositions/" >/dev/null
guest wait --for=condition=Established xrd/previewenvironments.preview.platform.example.org --timeout=2m >/dev/null
for ((attempt=0; attempt<60; attempt++)); do
  if [[ $(guest auth can-i create namespaces --as=system:serviceaccount:crossplane-system:crossplane 2>/dev/null) == yes && \
        $(guest auth can-i create deployments.apps --namespace=default --as=system:serviceaccount:crossplane-system:crossplane 2>/dev/null) == yes ]]; then
    break
  fi
  sleep 2
done
(( attempt < 60 )) || { echo "candidate-preview: virtual Crossplane RBAC is not ready" >&2; exit 1; }

child_name=$(python3 - "$child_xr" <<'PY'
import json,sys
with open(sys.argv[1], encoding="utf-8") as source:
    print(json.load(source)["metadata"]["name"])
PY
)
guest apply -f "$child_xr" >/dev/null
for ((attempt=0; attempt<150; attempt++)); do
  if guest get "previewenvironment/$child_name" -o json | python3 -c '
import json,sys
obj=json.load(sys.stdin)
generation=obj["metadata"].get("generation", 0)
head=obj.get("spec",{}).get("pr",{}).get("headSHA")
conditions=obj.get("status",{}).get("conditions",[])
ready=any(c.get("type")=="Ready" and c.get("status")=="True" and c.get("observedGeneration",0)>=generation for c in conditions)
synced=any(c.get("type")=="Synced" and c.get("status")=="True" and c.get("observedGeneration",0)>=generation for c in conditions)
sys.exit(0 if generation and head==sys.argv[1] and ready and synced else 1)
' "$head"; then break; fi
  sleep 2
done
(( attempt < 150 )) || { echo "candidate-preview: child XR did not become ready at the current head" >&2; exit 1; }
guest -n "$child_name" get deployment/incident-tracker service/incident-tracker ingress/incident-tracker >/dev/null
echo "candidate-preview: PASS $name: candidate Function rendered ready child XR $child_name"
