apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: preview-vcluster
spec:
  compositeTypeRef:
    apiVersion: preview.platform.example.org/v1alpha1
    kind: PreviewEnvironment
  mode: Pipeline
  pipeline:
    - step: render-preview-resources
      functionRef:
        name: function-preview-resources
      input:
        apiVersion: preview.fn.platform.example.org/v1alpha1
        kind: PreviewResourcesInput
        mode: vcluster
